apiVersion: v1 
kind: Pod
metadata:
 name: hello-world
spec:
  containers:
  - name: hello-world
    image: nrezaee/hello_world:latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: ".1"
        memory: "100Mi"
      limits:
        cpu: ".2"
        memory: "200Mi"
    command: ["/bin/bash", "-c" ]
    args:
      - python3 hello_world.py                          